/*
*
* Write your custom JavaScript here.
*
*/

jQuery(document).ready(function($){

    //Generates calendar for all acf-field-text that has class 'has-datepicker'
    $('.acf-field-text.has-datepicker').each(function() {
        var field_id = $(this).find('input').attr('id');
        generateCitynetCalendar(field_id);
        });

    //Adds read only style for all acf-field-text that has class 'read-only'
    $('.acf-field-text.read-only').each(function() {
        var field_id = $(this).find('input').attr('id');
        $('#' + field_id).prop({
            readonly: true,
            title: 'این فیلد بصورت خودکار مقدار خواهد گرفت',
            style: 'cursor: default; background-color: #eceaea !important;'
        });
    });

    var selectedCountries = [];
    //if current page has 'country selector ACF field':
    if ($('#select-countries').length == 1) {
        //get an ID list of before selected countries
        $('#select-countries .values .acf-rel-item').each(function() {
            selectedCountries.push($(this).data('id'));
        });
        //checks while all site's countries will be shown to sign selected before countries
        var countriesListChecker = setInterval(function() {
            if ($('#select-countries .choices .acf-rel-item').length > 0) {
                //add class 'selected-once' to selected before countries
                $('#select-countries .choices .acf-rel-item.disabled').addClass('selected-before');
                //stop checker timer
                clearInterval(countriesListChecker);
            }
        }, 100);
        //checks while all site's countries will be shown to sign selected before countries
        var citiesListChecker = setInterval(function() {
            if ($('#select-cities .choices .acf-rel-item').length > 0) {
                //clear selectable cities list - this list will be generated by our algorithm
                $('#select-cities .choices-list').empty();
                //stop checker timer
                clearInterval(citiesListChecker);
                //request cities by our algorithm
                fetch_cities_of_selected_countries();
            }
        }, 100);
    }

    //add new selected country's id to selected countries list and fetch cities list...
    $(document).on('click', '#select-countries .choices .acf-rel-item:not(.selected-before)', function() {
        selectedCountries.push($(this).data('id'));
        $(this).addClass('selected-before');
        //request cities by our algorithm
        fetch_cities_of_selected_countries();
    });

    function fetch_cities_of_selected_countries() {
        if (selectedCountries.length > 0) {
            var requestData = {
                action : 'citynet_cities_of_selected_countries_ajax_request',
                countriesID : selectedCountries
            }
            $.ajax({
                url    : wpAdminGeneralData.ajaxurl,
                data   : requestData,
                success: function(response) {
                    //clear selectable cities list - this list will be generated by our algorithm
                    $('#select-cities .choices-list').empty();

                    //add each city as a li html to selectable cities list
                    var citiesInfo = JSON.parse(response);
                    citiesInfo.forEach(function(city) {
                        $('#select-cities .choices-list').append('<li><span class="acf-rel-item" data-id="' + city['id'] + '" data-country-id="' + city['country-id'] + '">' + city['title'] + '</span></li>');
                    });

                    //check on each selected cities, disable on right list and set country id for self
                    $('#select-cities .values .acf-rel-item').each(function() {
                        var cityID = $(this).data('id');
                        var cityInLeftList = $('#select-cities .choices .acf-rel-item[data-id="' + cityID + '"]');
                        cityInLeftList.addClass('disabled');
                        $(this).attr('data-country-id', cityInLeftList.data('country-id'));
                    });

                }
            });
        }
    }

    //when a country removed from right list
    $('#select-countries .values').on('click', '.acf-rel-item a', function() {
        var countryID = $(this).closest('.acf-rel-item').data('id');
        //delete country id from selected countries list
        selectedCountries.splice(selectedCountries.indexOf(countryID), 1);
        //delete class 'selected-before' from country in left list
        $('#select-countries .choices .acf-rel-item[data-id="' + countryID + '"]').removeClass('selected-before');
        //delete related cities in both of cities list
        $('#select-cities .acf-rel-item[data-country-id="' + countryID + '"]').closest('li').remove();
    });

    //when select new city, copy country id from left list to self in right list
    $(document).on('click', '#select-cities .choices .acf-rel-item', function() {
        var cityID = $(this).data('id');
        $('#select-cities .values .acf-rel-item[data-id="' + cityID + '"]').attr('data-country-id', $(this).data('country-id'));
    });

});

//Generates calendar for selected element by ID
function generateCitynetCalendar(elementId) {
    var field_key = elementId;
    var field_id = '#' + field_key;
    var calendarName = jQuery(field_id).closest('.has-datepicker').attr('data-name');

    var acf_date = new AMIB.datePicker(field_key, {
        supportGregorian: true,
        onchange: function() {
            if (calendarName == 'hd-holding-date') {
                jQuery(field_id).closest('.acf-row').find('.acf-field-text[data-name="hd-package-validation-date"] input').val(jQuery(field_id).val());
            }
        }
    });
    acf_date.setMinDate(0, 0, AMIB.getTodayJD());

    jQuery(field_id).prop({
        readonly: true,
        title: 'انتخاب تاریخ',
        style: 'cursor: pointer;'
    });
}